trigger: none

pool:
  vmImage: 'ubuntu-latest'

variables: 
  - group: InternalKeys
  
stages:

- stage: Data
  jobs:
  - job: Get_TAC_CSV_DataFile
    steps:
    - task: Bash@3
      displayName: 'Download TAC V4 CSV data file'
      inputs:
        targetType: 'inline'
        script: 'wget "https://distributor.51degrees.com/api/v2/download?LicenseKeys=$(DeviceDetectionLicenseKey)&Type=21&Download=True&Product=23" -O "$(Build.SourcesDirectory)/51Degrees-Tac.zip"'
  
    - task: Bash@3
      displayName: 'Extract TAC V4 CSV data file'
      inputs:
        targetType: 'inline'
        script: 'unzip -p $(Build.SourcesDirectory)/51Degrees-Tac.zip 51Degrees-Tac-All.csv > $(Build.ArtifactStagingDirectory)/51Degrees.csv'
        workingDirectory: '$(Build.SourcesDirectory)'

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'tacFile'
        publishLocation: 'Container'
        
- stage: Build_and_Test
  dependsOn: [Data]
  
  jobs:
  
  - job: Build_And_Test

    strategy:
      matrix:
        PHP 5.6:
          phpVersion: 5.6
        PHP 7.2:
          phpVersion: 7.2
        PHP 7.3:
          phpVersion: 7.3
        PHP 7.4:
          phpVersion: 7.4
    
    steps:
    - script: |
        sudo update-alternatives --set php /usr/bin/php$(phpVersion)
        sudo update-alternatives --set phar /usr/bin/phar$(phpVersion)
        sudo update-alternatives --set phpdbg /usr/bin/phpdbg$(phpVersion)
        sudo update-alternatives --set php-cgi /usr/bin/php-cgi$(phpVersion)
        sudo update-alternatives --set phar.phar /usr/bin/phar.phar$(phpVersion)
        php -version
      displayName: 'Use PHP version $(phpVersion)'
    
    - task: DownloadBuildArtifacts@0
      displayName: 'Download TAC CSV File'
      inputs:
        buildType: 'current'
        downloadType: 'single'
        artifactName: 'tacFile'
        downloadPath: '$(System.ArtifactsDirectory)'
    
    - script: |
          mv $(System.ArtifactsDirectory)/tacFile/51Degrees.csv  $(Build.SourcesDirectory)/tests/51Degrees.csv
      displayName: 'Move TAC data File'
        
    - script: |
            composer install --no-interaction --prefer-dist -vvv
      displayName: 'Install dependencies'
    
    - script: |
        sudo rm -r /usr/local/bin/phpunit
        wget -O phpunit https://phar.phpunit.de/phpunit-5.phar
        chmod +x phpunit
        sudo mv phpunit /usr/local/bin/phpunit
      displayName: 'install PHPUnit 5'
      condition: eq(variables['phpVersion'], '5.6')
    
    - script: |
        sed -i 's,.*name="RESOURCEKEY".*$,<env name="RESOURCEKEY" value="$(SuperResourceKey)" force="true"/>,' phpunit.xml
        sed -i 's,.*name="FOD_CLOUD_API_URL".*$,<env name="FOD_CLOUD_API_URL" value="$(FOD_CLOUD_API_URL)" force="true"/>,' phpunit.xml
        cat phpunit.xml
      displayName: 'Set resource key and cloud endpoint'
    
    - script: |
        phpunit --log-junit test-results.xml
      displayName: 'Run tests with phpunit'
      
    # Publish Test Results to Azure Pipelines/TFS
    - task: PublishTestResults@2
      inputs:
        testRunner: 'JUnit'
        testResultsFiles: '**/test-results.xml'
        searchFolder: '$(System.DefaultWorkingDirectory)'
        mergeTestResults: false
        testRunTitle: '$(phpVersion)'
      condition: always()
